apiVersion: v1
kind: Service
metadata:
  name: myimagespring
  labels:
    app: myimagespring
spec:
  selector:
    app: myimagespring
  ports:
    - protocol: "TCP"
      port: 9090
      targetPort: 9090
  type: NodePort