
name: Build and Publish Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'

      - name: Build and push backend Docker image
        run: |
          mvn package
          docker build . --tag ghcr.io/angelacebrian/docassignment
          docker push ghcr.io/angelacebrian/docassignment

      - name: Build and push PostgreSQL Docker image
        run: docker pull postgres:14.1-alpine
        # Additional steps to customize and push the PostgreSQL image if needed

      # Add more steps for other services if necessary

