name: Run Tests and Archive Code Coverage

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'

      - name: Start Docker Compose
        run: docker-compose -f "docker-compose.yml" up -d

      - name: Wait for Containers to Start
        run: sleep 30  # Adjust as needed to allow time for containers to start

      - name: Run Tests
        run: mvn compile test

      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: test-coverage-report
          path: target/site/jacoco/
          retention-days: 7

      - name: Stop Docker Compose
        run: docker-compose -f docker-compose.test.yaml down

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: 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

      - name: Build and publish updated image
        run: |
          mvn package
          docker build . --tag ghcr.io/angelacebrian/docassignment
          docker push ghcr.io/angelacebrian/docassignment
